pipeline {
  agent {
    node {
      label 'MOCK' }
  }
  parameters {
	string(defaultValue: 'admin', description: 'Your name', name: 'USER_NAME')
	}
  environment {
    BUILD_RESULTS_EMAIL_LIST = "nthau3@tma.com.vn;"
    GIT_NAME = "mountebank-psx"
    APP_NAME = "PSX MOCK API SERVER"
  }

  options {
    timestamps()
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr:'20'))
  }

  stages {
    stage('First stage') {
      steps {
        // Setup OS VM
        sh '''
                echo hello ${USER_NAME}
        '''
      }
    }

    stage('Build') {
       steps {
          withCredentials([usernamePassword(credentialsId: 'bit', usernameVariable: 'VSEBLD', passwordVariable: 'VSEBLD_PASS')]) {
          sh '''
              rm -rf test-repo
              git clone http://$VSEBLD:$VSEBLD_PASS@bitbucket.rbbn.com/scm/~hnguyenthanh/test-repo.git
              cd test-repo
              ls
          '''
          }
        }
    }
  }
   post {
    failure {
      emailext body: "Build URL is: ${BUILD_URL}",
      recipientProviders: [
        [$class: 'DevelopersRecipientProvider']
      ],
      subject: "[Jenkins] Pipeline for $GIT_NAME - Build #${BUILD_NUMBER} - BUILD FAILING",
      to: "$BUILD_RESULTS_EMAIL_LIST"
    }

    unstable {
      emailext body: "MOCK API SERVER build UNSTABLE.\n",
      recipientProviders: [
        [$class: 'DevelopersRecipientProvider']
      ],
      subject: "[Jenkins] Pipeline for $GIT_NAME - Build #${BUILD_NUMBER} - BUILD Unstable",
      to: "$BUILD_RESULTS_EMAIL_LIST"
    }
  }
}

